name: BattleLab
favicon: null
layout_spectrum: 0.39339
typography_spectrum: 0.7033156405668706
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5625
  lightness: 0.47438587341457605
  saturation: 0.5181173176970333
  rhythmicContrast: 0.5961833545006812
purpose: []
